//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPGoogleChart
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleChartData
    {
        public int SLID { get; set; }
        public int Year { get; set; }
        public int Electronics { get; set; }
        public int BookAndMedia { get; set; }
        public int HomeAndKitchen { get; set; }
    }
}
